global:
  scrape_interval: 5s
scrape_configs:
  - job_name: node
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - node_monitor:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: disk-usage
    scrape_interval: 20s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - disk_usage_monitor:9995
  - job_name: caddy
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets:
        - caddy:2018
  - job_name: grafana
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - grafana:3000
